// SignUp Constant
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// verify Success
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

// SignIn
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

// Logout
export const LOGOUT_USER = 'LOGOUT_USER'

// Product List
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

// Product Add
export const PRODUCT_ADD_REQUEST='PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS='PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL='PRODUCT_ADD_FAIL';

// Product Edit
export const PRODUCT_EDIT_REQUEST='PRODUCT_EDIT_REQUEST';
export const PRODUCT_EDIT_SUCCESS='PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL='PRODUCT_EDIT_FAIL';

// Product Update
export const PRODUCT_UPDATE_REQUEST='PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS='PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL='PRODUCT_UPDATE_FAIL';

// Product Delete
export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL='PRODUCT_DELETE_FAIL';

// Order LIst
export const ORDER_LIST_REQUEST='ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS='ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL='ORDER_LIST_FAIL';

//EXPENSE_CATEGORY_SAVE_REQUEST
export const EXPENSE_CATEGORY_SAVE_REQUEST = "EXPENSE_CATEGORY_SAVE_REQUEST"
export const EXPENSE_CATEGORY_SAVE_SUCCESS = "EXPENSE_CATEGORY_SAVE_SUCCESS"
export const EXPENSE_CATEGORY_SAVE_FAIL = "EXPENSE_CATEGORY_SAVE_FAIL"
//EXPENSE_CATEGORY _GET_ REQUEST
export const EXPENSE_CATEGORY_TABLE_REQUEST = "EXPENSE_CATEGORY_TABLE_REQUEST"
export const EXPENSE_CATEGORY_TABLE_SUCCESS = "EXPENSE_CATEGORY_TABLE_SUCCESS"
export const EXPENSE_CATEGORY_TABLE_FAIL = "EXPENSE_CATEGORY_TABLE_FAIL"
//EXPENSE _CATEGORY_EDIT _REQUEST
export const EXPENSE_CATEGORY_EDIT_REQUEST = "EXPENSE_CATEGORY_EDIT_REQUEST"
export const EXPENSE_CATEGORY_EDIT_SUCCESS = "EXPENSE_CATEGORY_EDIT_SUCCESS"
export const EXPENSE_CATEGORY_EDIT_FAIL = "EXPENSE_CATEGORY_EDIT_FAIL"
//EXPENSE_CATEGORY_ DELETE_REQUEST
export const EXPENSE_CATEGORY_DELETE_REQUEST = "EXPENSE_CATEGORY_DELETE_REQUEST"
export const EXPENSE_CATEGORY_DELETE_SUCCESS = "EXPENSE_CATEGORY_DELETE_SUCCESS"
export const EXPENSE_CATEGORY_DELETE_FAIL = "EXPENSE_CATEGORY_DELETE_FAIL"
//EXPENSE _CATEGORY_UPDATE_REQUEST
export const EXPENSE_CATEGORY_UPDATE_REQUEST = "EXPENSE_CATEGORY_UPDATE_REQUEST"
export const EXPENSE_CATEGORY_UPDATE_SUCCESS = "EXPENSE_CATEGORY_UPDATE_SUCCESS"
export const EXPENSE_CATEGORY_UPDATE_FAIL = "EXPENSE_CATEGORY_UPDATE_FAIL"
//INCOME_CATEGORY_SAVE_REQUEST
export const INCOME_CATEGORY_SAVE_REQUEST = "INCOME_CATEGORY_SAVE_REQUEST"
export const INCOME_CATEGORY_SAVE_SUCCESS = "INCOME_CATEGORY_SAVE_SUCCESS"
export const INCOME_CATEGORY_SAVE_FAIL = "INCOME_CATEGORY_SAVE_FAIL"
//INCOME_CATEGORY _GET_ REQUEST
export const INCOME_CATEGORY_TABLE_REQUEST = "INCOME_CATEGORY_TABLE_REQUEST"
export const INCOME_CATEGORY_TABLE_SUCCESS = "INCOME_CATEGORY_TABLE_SUCCESS"
export const INCOME_CATEGORY_TABLE_FAIL = "INCOME_CATEGORY_TABLE_FAIL"
//INCOME _CATEGORY_EDIT _REQUEST
export const INCOME_CATEGORY_EDIT_REQUEST = "INCOME_CATEGORY_EDIT_REQUEST"
export const INCOME_CATEGORY_EDIT_SUCCESS = "INCOME_CATEGORY_EDIT_SUCCESS"
export const INCOME_CATEGORY_EDIT_FAIL = "INCOME_CATEGORY_EDIT_FAIL"
//INCOME_CATEGORY_ DELETE_REQUEST
export const INCOME_CATEGORY_DELETE_REQUEST = "INCOME_CATEGORY_DELETE_REQUEST"
export const INCOME_CATEGORY_DELETE_SUCCESS = "INCOME_CATEGORY_DELETE_SUCCESS"
export const INCOME_CATEGORY_DELETE_FAIL = "INCOME_CATEGORY_DELETE_FAIL"
//INCOME _CATEGORY_UPDATE_REQUEST
export const INCOME_CATEGORY_UPDATE_REQUEST = "INCOME_CATEGORY_UPDATE_REQUEST"
export const INCOME_CATEGORY_UPDATE_SUCCESS = "INCOME_CATEGORY_UPDATE_SUCCESS"
export const INCOME_CATEGORY_UPDATE_FAIL = "INCOME_CATEGORY_UPDATE_FAIL"
//EXPENSES FORM REQUEST
export const EXPENSES_SAVE_REQUEST = "EXPENSES_SAVE_REQUEST"
export const EXPENSES_SAVE_SUCCESS = "EXPENSES_SAVE_SUCCESS"
export const EXPENSES_SAVE_FAIL = "EXPENSES_SAVE_FAIL"
//EXPENSES GET REQUEST
export const EXPENSES_TABLE_REQUEST = "EXPENSES_TABLE_REQUEST"
export const EXPENSES_TABLE_SUCCESS = "EXPENSES_TABLE_SUCCESS"
export const EXPENSES_TABLE_FAIL = "EXPENSES_TABLE_FAIL"
//EXPENSES EDIT REQUEST
export const EXPENSES_EDIT_REQUEST = "EXPENSES_EDIT_REQUEST"
export const EXPENSES_EDIT_SUCCESS = "EXPENSES_EDIT_SUCCESS"
export const EXPENSES_EDIT_FAIL = "EXPENSES_EDIT_FAIL"
//EXPENSES DELETE REQUEST
export const EXPENSES_DELETE_REQUEST = "EXPENSES_DELETE_REQUEST"
export const EXPENSES_DELETE_SUCCESS = "EXPENSES_DELETE_SUCCESS"
export const EXPENSES_DELETE_FAIL = "EXPENSES_DELETE_FAIL"
//EXPENSES UPDATEREQUEST
export const EXPENSES_UPDATE_REQUEST = "EXPENSES_UPDATE_REQUEST"
export const EXPENSES_UPDATE_SUCCESS = "EXPENSES_UPDATE_SUCCESS"
export const EXPENSES_UPDATE_FAIL = "EXPENSES_UPDATE_FAIL"
//INCOME FORM REQUEST
export const INCOME_SAVE_REQUEST = "INCOME_SAVE_REQUEST"
export const INCOME_SAVE_SUCCESS = "INCOME_SAVE_SUCCESS"
export const INCOME_SAVE_FAIL = "INCOME_SAVE_FAIL"
//INCOME GET REQUEST
export const INCOME_TABLE_REQUEST = "INCOME_TABLE_REQUEST"
export const INCOME_TABLE_SUCCESS = "INCOME_TABLE_SUCCESS"
export const INCOME_TABLE_FAIL = "INCOME_TABLE_FAIL"
//INCOME EDIT REQUEST
export const INCOME_EDIT_REQUEST = "INCOME_EDIT_REQUEST"
export const INCOME_EDIT_SUCCESS = "INCOME_EDIT_SUCCESS"
export const INCOME_EDIT_FAIL = "INCOME_EDIT_FAIL"
//INCOME DELETE REQUEST
export const INCOME_DELETE_REQUEST = "INCOME_DELETE_REQUEST"
export const INCOME_DELETE_SUCCESS = "INCOME_DELETE_SUCCESS"
export const INCOME_DELETE_FAIL = "INCOME_DELETE_FAIL"
//EXPENSES UPDATEREQUEST
export const INCOME_UPDATE_REQUEST = "INCOME_UPDATE_REQUEST"
export const INCOME_UPDATE_SUCCESS = "INCOME_UPDATE_SUCCESS"
export const INCOME_UPDATE_FAIL = "INCOME_UPDATE_FAIL"
// Profile
export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_FAIL = "PROFILE_FAIL"
// Update request
export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST"
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL"
// Sales report
export const SALES_ALL_REQUEST = "SALES_ALL_REQUEST"
export const SALES_ALL_SUCCESS = "SALES_ALL_SUCCESS"
export const SALES_ALL_FAIL = "SALES_ALL_FAIL"

